### PR TITLE
Added void linux install instructions

### PR DESCRIPTION
**Pull request by caughtquick**
I maintain the bpytop packages in the void repos

### CODE REVIEW

**Comment by aristocratos** [comment]
@caughtquick 
Sure thing, will merge, but please move it to the section with the other linux distribution packages first, instead of after the instructions for manual installation.

**Comment by caughtquick** [comment]
I think I fixed it @aristocratos, sorry for the long delay

**Comment by aristocratos** [comment]
@caughtquick 
Thanks, will merge in next update.

**Comment by caughtquick** [comment]
Thank you :)

**Pull request merged**
