### PR TITLE
Add test setup and initial tests

### PR DESCRIPTION
**Pull request by ErwinJunge**
I noticed there aren't any tests in this repo, so I took it upon myself to implement the basics of automated testing using tox and travis.

I think you have to sign up (free) first to enable this for the repo over at https://travis-ci.com/ and then you'll get free automated tests on each PR.

Example output: https://travis-ci.com/github/ErwinJunge/bpytop/builds/192811631

Additionally I've added some simple tests for the terminal title (to test the implementation of the tests really, very meta).

Since I'm a big fan of tests and test-driven development, I'll probably contribute some more tests but having this plumbing in place allows anyone to do so. To run them yourself, just type `tox` :)

### CODE REVIEW

**Comment by ErwinJunge** [comment]
Oh hey, it actually already works! https://github.com/aristocratos/bpytop/pull/165/checks?check_run_id=1309381037 :sunglasses:

**Comment by aristocratos** [comment]
@ErwinJunge 
> I noticed there aren't any tests in this repo, so I took it upon myself to implement the basics of automated testing using tox and travis.

Awesome, thank you :) I had been meaning to get to it.

> Oh hey, it actually already works!

Yeah, I enabled travis for bashtop, I guess it was enabled for all my repositories then.

> Since I'm a big fan of tests and test-driven development, I'll probably contribute some more tests

That would be very welcome. Let me know if there is anything in particular you wanna write test for that's not completely clear what it's supposed to do.

Will merge this later today since "All checks have passed" :)

**Comment by aristocratos** [comment]
Had some problems getting `tox` to work, seems it's a problem with the one packaged with ubuntu, works fine when installing with `pip` though.

**Comment by aristocratos** [comment]
@ErwinJunge 
Is there an easy way to setup something like `mypy *.py` and `pylint -E *.py` to run as two seperate tests aswell?

**Comment by ErwinJunge** [comment]
> @ErwinJunge
> Is there an easy way to setup something like `mypy *.py` and `pylint -E *.py` to run as two seperate tests aswell?

https://github.com/aristocratos/bpytop/pull/170 :sunglasses:

**Pull request merged**
